# Generated by Django 2.0.1 on 2018-01-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('codeClient', models.CharField(max_length=20)),
                ('nomPrenomClient', models.CharField(max_length=100)),
                ('matFiscalClient', models.CharField(max_length=100)),
                ('addresseClient1', models.CharField(max_length=100)),
                ('addresseClient2', models.CharField(max_length=100)),
                ('numTelClient1', models.IntegerField()),
                ('numTelClient2', models.IntegerField()),
            ],
            options={
                'db_table': 'client',
                'ordering': ['codeClient'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('idClient', 'codeClient')},
        ),
    ]
